
spring:
  data:
    mongodb:
      authentication-database: admin
      port: 27017
      host: localhost
      database: ProductDB
  application:
    name: spring-data-mongoDB

  banner:
    charset: UTF-8



