
spring:
  data:
    mongodb:
      authentication-database: admin
      port: 27017
      host: localhost
      database: ProductDB
  application:
    name: spring-mongodb-with-actuator

  banner:
    charset: UTF-8

# Configuration of spring actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'



